import React from 'react';
import Link from 'next/link';
import { Container } from '@/components/ui/Container';
import { ResponsiveImage } from '@/components/ui/ResponsiveImage';
import { siteConfig } from '@/lib/config';
import { GlobeAltIcon, HeartIcon, SparklesIcon, PhoneIcon, StarIcon, MapPinIcon, ArrowRightIcon, } from '@heroicons/react/24/outline';
const stats = [
    { value: '500+', label: 'Happy Travellers' },
    { value: '10+', label: 'Destinations Covered' },
    { value: '4.9★', label: 'Average Rating' },
    { value: '24/7', label: 'WhatsApp Support' },
];
const values = [
    {
        icon: HeartIcon,
        title: 'Personal Care',
        description: 'Every trip is personally planned — not generated by an algorithm. We take time to understand your preferences and craft a truly custom experience.',
        color: '#EC4899',
    },
    {
        icon: GlobeAltIcon,
        title: 'Local Expertise',
        description: 'Deep, on-the-ground knowledge of Kashmir Valley combined with trusted international travel partners across 10+ destinations worldwide.',
        color: '#0A3D62',
    },
    {
        icon: StarIcon,
        title: 'Premium Quality',
        description: 'We partner only with verified 4-star and 5-star properties, experienced local guides, and comfortable private transport for every trip.',
        color: '#D4AF37',
    },
    {
        icon: SparklesIcon,
        title: 'Transparent Value',
        description: 'No hidden charges. Every price includes what is listed. We believe honest pricing builds trust — and trust builds lasting relationships.',
        color: '#22C55E',
    },
];
const teamHighlights = [
    'Kashmir-born travel specialist with years of local expertise',
    'Direct personal WhatsApp access — not a call centre',
    'Trusted by solo travellers, families, couples & corporate groups',
    'Curated network of partner hotels, guides & transport operators',
    'Itineraries designed after understanding your preferences, not templates',
];
const whatsappUrl = `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent(`Hi ${siteConfig.ownerName}, I'd like to know more about your travel agency.`)}`;
export const metadata = {
    title: `About Us | ${siteConfig.name}`,
    description: 'Learn about Tours & Travels — a personally-run travel consultancy specialising in Kashmir valley journeys and international luxury packages.',
};
export default function AboutPage() {
    return (<div className="flex flex-col min-h-screen bg-[#F8FAFC]">
      {/* ── HERO ── */}
      <section className="relative overflow-hidden bg-[#0A3D62] text-white py-20 sm:py-28">
        <ResponsiveImage src="/images/kashmir.jpg" alt="About our travel agency" priority className="absolute inset-0 w-full h-full object-cover opacity-25" width={1920} height={1080}/>
        <div className="absolute inset-0 bg-gradient-to-b from-[#0A3D62]/80 via-[#0A3D62]/60 to-[#0A3D62]"/>
        <Container className="relative z-10 text-center max-w-3xl">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-[#D4AF37]/20 border border-[#D4AF37]/40 text-[#D4AF37] text-xs font-semibold uppercase tracking-widest mb-6">
            <MapPinIcon className="h-4 w-4"/>
            <span>Our Story</span>
          </div>
          <h1 className="font-playfair text-4xl sm:text-5xl md:text-6xl font-bold mb-5 leading-tight">
            Travel Crafted with<br />
            <span className="text-[#D4AF37]">Passion & Purpose</span>
          </h1>
          <p className="font-inter text-lg text-gray-200 max-w-2xl mx-auto leading-relaxed">
            We are {siteConfig.name} — a personally-run travel consultancy dedicated to creating unforgettable journeys across Kashmir and the world.
          </p>
        </Container>
      </section>

      {/* ── STATS ── */}
      <section className="py-10 bg-white border-b border-gray-100">
        <Container className="max-w-4xl">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 text-center">
            {stats.map((stat) => (<div key={stat.label} className="p-4">
                <div className="font-playfair text-4xl font-bold text-[#0A3D62] mb-1">{stat.value}</div>
                <div className="font-inter text-sm text-gray-500 uppercase tracking-wide">{stat.label}</div>
              </div>))}
          </div>
        </Container>
      </section>

      {/* ── STORY SECTION ── */}
      <section className="py-16 sm:py-24">
        <Container className="max-w-5xl">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="relative rounded-2xl overflow-hidden aspect-[3/4] shadow-xl">
              <ResponsiveImage src="/images/kashmir.jpg" alt="Kashmir valley — our home and expertise" className="w-full h-full object-cover" width={600} height={800}/>
              <div className="absolute inset-0 bg-gradient-to-t from-[#0A3D62]/70 to-transparent"/>
              <div className="absolute bottom-6 left-6 right-6 text-white">
                <p className="font-inter text-xs text-[#D4AF37] uppercase tracking-widest mb-1">Our Home</p>
                <p className="font-playfair text-2xl font-bold">Kashmir Valley</p>
                <p className="font-inter text-sm text-gray-200 mt-1">Where every journey begins</p>
              </div>
            </div>
            <div>
              <p className="text-[#D4AF37] font-semibold text-sm uppercase tracking-widest mb-2">Who We Are</p>
              <h2 className="font-playfair text-3xl sm:text-4xl font-bold text-[#0A3D62] mb-6 leading-snug">
                A Travel Specialist Who<br />Treats You Like Family
              </h2>
              <div className="space-y-4 font-inter text-gray-600 leading-relaxed text-[15px]">
                <p>
                  {siteConfig.name} was built on a simple belief: travel should be personal. When you reach out to us, you speak directly to <strong className="text-[#0A3D62]">{siteConfig.ownerName}</strong> — the person who will personally plan, coordinate, and support your entire journey.
                </p>
                <p>
                  Born and raised with a deep love for the Kashmir Valley, we built our expertise around one of India&apos;s most breathtaking destinations — and expanded to curate luxury international packages to Dubai, Maldives, Switzerland, Thailand, Singapore and Paris.
                </p>
                <p>
                  Whether you are a solo adventurer, a couple planning a honeymoon, a family seeking new horizons, or a group looking for a group getaway — we have a package or will build one just for you.
                </p>
              </div>
              <div className="mt-8">
                <ul className="space-y-3">
                  {teamHighlights.map((item) => (<li key={item} className="flex items-start gap-3 font-inter text-gray-600 text-sm">
                      <StarIcon className="h-5 w-5 flex-shrink-0 text-[#D4AF37] mt-0.5"/>
                      {item}
                    </li>))}
                </ul>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* ── OUR VALUES ── */}
      <section className="py-16 sm:py-24 bg-[#0A3D62] text-white">
        <Container className="max-w-5xl">
          <div className="text-center mb-14">
            <p className="text-[#D4AF37] font-semibold text-sm uppercase tracking-widest mb-2">Our Foundation</p>
            <h2 className="font-playfair text-3xl sm:text-4xl font-bold mb-4">Values That Guide Every Journey</h2>
            <p className="text-gray-300 max-w-xl mx-auto font-inter">
              These are not just words. They are the principles we apply to every trip we plan.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {values.map((val) => (<div key={val.title} className="flex gap-5 p-6 rounded-2xl bg-white/10 border border-white/20">
                <div className="flex-shrink-0 inline-flex items-center justify-center w-12 h-12 rounded-xl" style={{ backgroundColor: `${val.color}25` }}>
                  <val.icon className="h-6 w-6" style={{ color: val.color }}/>
                </div>
                <div>
                  <h3 className="font-playfair text-xl font-bold mb-2">{val.title}</h3>
                  <p className="font-inter text-sm text-gray-300 leading-relaxed">{val.description}</p>
                </div>
              </div>))}
          </div>
        </Container>
      </section>

      {/* ── DESTINATIONS SHOWCASE ── */}
      <section className="py-16 sm:py-24">
        <Container className="max-w-5xl">
          <div className="text-center mb-12">
            <p className="text-[#D4AF37] font-semibold text-sm uppercase tracking-widest mb-2">Where We Take You</p>
            <h2 className="font-playfair text-3xl sm:text-4xl font-bold text-[#0A3D62] mb-4">Our Travel Destinations</h2>
            <p className="text-gray-500 max-w-xl mx-auto font-inter">
              From Himalayan valleys to tropical islands and European capitals.
            </p>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
            {[
            { name: 'Kashmir Valley', image: '/images/kashmir.jpg', tag: 'Signature' },
            { name: 'Dubai, UAE', image: '/images/dubai.jpg', tag: 'International' },
            { name: 'Maldives', image: '/images/international.jpg', tag: 'International' },
            { name: 'Switzerland', image: '/images/kashmir.jpg', tag: 'International' },
            { name: 'Thailand', image: '/images/hero-travel.jpg', tag: 'International' },
            { name: 'Paris, France', image: '/images/international.jpg', tag: 'International' },
        ].map((dest) => (<div key={dest.name} className="relative rounded-xl overflow-hidden aspect-[4/3] group">
                <ResponsiveImage src={dest.image} alt={dest.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" width={400} height={300}/>
                <div className="absolute inset-0 bg-gradient-to-t from-[#0A3D62]/80 to-transparent"/>
                <div className="absolute bottom-3 left-3 text-white">
                  <p className="font-inter text-[10px] text-[#D4AF37] uppercase tracking-widest">{dest.tag}</p>
                  <p className="font-playfair text-sm font-bold">{dest.name}</p>
                </div>
              </div>))}
          </div>
          <div className="text-center mt-8">
            <Link href="/#destinations" className="inline-flex items-center gap-2 text-[#0A3D62] font-semibold font-inter hover:text-[#D4AF37] transition-colors">
              View All Destinations
              <ArrowRightIcon className="h-4 w-4"/>
            </Link>
          </div>
        </Container>
      </section>

      {/* ── CTA ── */}
      <section className="py-16 bg-gradient-to-r from-[#D4AF37] to-[#B8952A] text-white">
        <Container className="max-w-3xl text-center">
          <h2 className="font-playfair text-3xl sm:text-4xl font-bold mb-4">Let&apos;s Plan Your Next Adventure</h2>
          <p className="font-inter text-lg mb-8 text-yellow-100">
            Reach out to {siteConfig.ownerName} on WhatsApp for a free, no-obligation travel consultation.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-3 bg-white text-[#B8952A] font-bold px-8 py-4 rounded-xl text-lg hover:bg-yellow-50 transition-colors shadow-lg">
              <PhoneIcon className="h-6 w-6"/>
              Chat on WhatsApp
            </a>
            <Link href="/contact" className="inline-flex items-center gap-2 bg-white/20 border border-white/40 text-white font-semibold px-8 py-4 rounded-xl text-lg hover:bg-white/30 transition-colors">
              Send an Inquiry
              <ArrowRightIcon className="h-5 w-5"/>
            </Link>
          </div>
        </Container>
      </section>
    </div>);
}
